name: Reusable file
on: 
    workflow_call:
     inputs:
        artifact-name:
            description: 'Deploy the website'
            required: true
            default: dist
            type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get build artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
      - name: Output contents
        run: ls
      - name: Deploy
        run: |
         echo "Deploying..."
         echo "Cyber Deployment complete."